// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/exam/domain/use_cases/fetch_exam_questions_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:exam_app/config/base_response/base_response.dart' as _i4;
import 'package:exam_app/features/exam/domain/entity/question_entity.dart'
    as _i5;
import 'package:exam_app/features/exam/domain/repo/exam_repo_contract.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ExamRepoContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamRepoContract extends _i1.Mock implements _i2.ExamRepoContract {
  MockExamRepoContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i5.QuestionEntity>>> fetchExamQuestions(
    String? examId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchExamQuestions, [examId]),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i5.QuestionEntity>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i5.QuestionEntity>>>(
                    this,
                    Invocation.method(#fetchExamQuestions, [examId]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i5.QuestionEntity>>>);
}
