// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/features/exam/api/data_source/remote/exam_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:exam_app/features/exam/api/api_client/exam_api_client.dart'
    as _i3;
import 'package:exam_app/features/exam/data/models/exam_questions_response/exam_questions_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeExamQuestionsResponse_0 extends _i1.SmartFake
    implements _i2.ExamQuestionsResponse {
  _FakeExamQuestionsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExamApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamApiClient extends _i1.Mock implements _i3.ExamApiClient {
  MockExamApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ExamQuestionsResponse> fetchExamQuestions({
    required String? examId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchExamQuestions, [], {#examId: examId}),
            returnValue: _i4.Future<_i2.ExamQuestionsResponse>.value(
              _FakeExamQuestionsResponse_0(
                this,
                Invocation.method(#fetchExamQuestions, [], {#examId: examId}),
              ),
            ),
          )
          as _i4.Future<_i2.ExamQuestionsResponse>);
}
